name=board001
version=1.0.0
license=MIT
author=Beck Ye <mynewworldyyl@gmail.com>
maintainer=Beck Ye <mynewworldyyl@gmail.com>
sentence=RPC and Message service provided by JMicro platform.
paragraph=support any platform.
category=Communication
url=https://github.com/mynewworldyyl/jm_client
repository=https://github.com/mynewworldyyl/jm_client.git
architectures=*
