[platformio]
src_dir = src
lib_dir = lib
default_envs = stm32f1_blackpill

; framework = stm32cube → framework = cmsis
;  -DUSE_HAL_UART

;platform = ststm32
;framework = cmsis

[env]
platform = ststm32
;framework = stm32cube
framework = cmsis
upload_protocol = stlink
upload_flags = -c set CPUTAPID 0x2ba01477
monitor_speed = 115200
build_type = release
lib_extra_dirs =
    ../jm_stm32

; 日志输出开关：0=关闭(默认)�?=开�?; 开启后使用 USART2(PA2) 输出日志，仅 TX�?15200 波特�?build_flags =

; stm32f1_bluepill (STM32F103C6)
[env:stm32f1_bluepill]
board = bluepill_f103c6
build_flags =
    -DSTM32F103xC
lib_extra_dirs =
    ../jm_stm32

; stm32f1_blackpill (STM32F103C8)
[env:stm32f1_blackpill]
board = bluepill_f103c8
build_flags =
 ;   -DUSE_HAL_UART
    -DSTM32F103xB
    -I../jm_stm32/jm_stm32_boards/board001

; stm32f103_nucleo64 (STM32F103RB)
[env:stm32f103_nucleo64]
board = nucleo_f103rb
build_flags =
    -DSTM32F103xB
lib_extra_dirs =
    ../jm_stm32

; stm32f411_nucleo64 (STM32F411RE)
[env:stm32f411_nucleo64]
board = nucleo_f411re
build_flags =
    -DSTM32F411xE
lib_extra_dirs =
    ../jm_stm32
